import type { Metadata } from 'next';
import './globals.css';
import { Provider } from 'jotai';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='cupcake'>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
